version: 0.2

env:
  variables:
    SONAR_SCANNER_VERSION: "4.8.0.2856"
    SONAR_SCANNER_DIR: "sonar-scanner-${SONAR_SCANNER_VERSION}-linux"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js dependencies...
      - npm install

      - echo Downloading SonarScanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/${SONAR_SCANNER_DIR}.zip
      - unzip sonar-scanner.zip
      - export PATH=$PWD/${SONAR_SCANNER_DIR}/bin:$PATH
      - sonar-scanner --version || echo "SonarScanner installed."

  pre_build:
    commands:
      - echo Setting up PATH for SonarScanner...
      - export PATH=$PWD/${SONAR_SCANNER_DIR}/bin:$PATH

      - echo Running SonarQube Analysis...
      - sonar-scanner \
          -Dsonar.projectKey=capstone_project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://3.87.231.29 \
          -Dsonar.login=sqp_38e05e8190e0253e620e2cc260bb3af31965a105

      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=418295691381
      - REGION=us-east-1
      - REPO_NAME=ecommerce-ecr
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}
      - echo Creating final deployment files...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}|g" k8s/deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/service.yaml k8s-out/
      - cp k8s/mongodb-*.yaml k8s-out/
      - ls -R k8s-out

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
    - mongodb-deployment.yaml
    - mongodb-service.yaml
